#!/system/bin/sh

if [[ ! -z $2 ]]; then
    filename=$(basename $2)
fi

if [[ ! -z $3 ]]; then
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
fi

chargeusbcurrent_predef="0"
chargeusbcurrent_find=`grep "chargeusbcurrent_predef" $DEFAULT_PROFILE | cut -d'=' -f2`

write_value() {  
  echo "$1=$2" >> $DEFAULT_PROFILE
}

edit_value() {
  g_find=`grep $1=.* $DEFAULT_PROFILE`
    
  if [[ -z $g_find ]]; then
    write_value $1 $2
  else
    sed -i "s/$1=[^ ]*/$1=$2/" $DEFAULT_PROFILE 
  fi
}

write_values(){
  edit_value charge_level_usb $charge_level_usb
  edit_value chargeusbcurrent_predef $chargeusbcurrent_predef 

  echo $charge_level_usb > /sys/kernel/charge_levels/charge_level_usb
}

case "$chargeusbcurrentpredef" in
  0)
    charge_level_usb="475"
    chargeusbcurrent_predef="0"
    write_values
    ;;
  1)
    charge_level_usb="500"
    chargeusbcurrent_predef="1"
    write_values
    ;;
  2)
    charge_level_usb="600"
    chargeusbcurrent_predef="2"
    write_values
    ;;
  3)
    charge_level_usb="700"
    chargeusbcurrent_predef="3"
    write_values
    ;;
  4)
    charge_level_usb="800"
    chargeusbcurrent_predef="4"
    write_values
    ;;
  5)
    charge_level_usb="900"
    chargeusbcurrent_predef="5"
    write_values
    ;;
  6)
    charge_level_usb="1000"
    chargeusbcurrent_predef="6"
    write_values
    ;;
  *)
    if [[ ! -z $chargeusbcurrent_find ]]; then
      chargeusbcurrent_predef="$chargeusbcurrent_find"
    fi 
    ;;
esac;

eval echo $chargeusbcurrent_predef
