#!/system/bin/sh

if [[ ! -z $2 ]]; then
    filename=$(basename $2)
fi

if [[ ! -z $3 ]]; then
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
fi

cpuclockmax_predef="0"
cpuclockmax_find=`grep "cpuclockmax_predef" $DEFAULT_PROFILE | cut -d'=' -f2`

write_value() {  
  echo "$1=$2" >> $DEFAULT_PROFILE
}

edit_value() {
  g_find=`grep $1=.* $DEFAULT_PROFILE`
    
  if [[ -z $g_find ]]; then
    write_value $1 $2
  else
    sed -i "s/$1=[^ ]*/$1=$2/" $DEFAULT_PROFILE 
  fi
}

write_values(){
  edit_value cpuinfo_max_freq $cpuinfo_max_freq
  edit_value scaling_max_freq $scaling_max_freq
  edit_value cpufreq_max_limit $cpufreq_max_limit
  edit_value cpuclockmax_predef $cpuclockmax_predef 

  chmod 777 /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq
  echo $cpuinfo_max_freq > /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq
  chmod 0644 /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq

  chmod 777 /sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_max_freq
  echo $cpuinfo_max_freq > /sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_max_freq
  chmod 0644 /sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_max_freq

  chmod 777 /sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_max_freq
  echo $cpuinfo_max_freq > /sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_max_freq
  chmod 0644 /sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_max_freq

  chmod 777 /sys/devices/system/cpu/cpu3/cpufreq/cpuinfo_max_freq
  echo $cpuinfo_max_freq > /sys/devices/system/cpu/cpu3/cpufreq/cpuinfo_max_freq
  chmod 0644 /sys/devices/system/cpu/cpu3/cpufreq/cpuinfo_max_freq

  chmod 777 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
  echo $scaling_max_freq > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
  chmod 0644 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

  chmod 777 /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
  echo $scaling_max_freq > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
  chmod 0644 /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq

  chmod 777 /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
  echo $scaling_max_freq > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
  chmod 0644 /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq

  chmod 777 /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq
  echo $scaling_max_freq > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq
  chmod 0644 /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq

  chmod 777 /sys/power/cpufreq_max_limit
  echo $cpufreq_max_limit > /sys/power/cpufreq_max_limit
  chmod 0644 /sys/power/cpufreq_max_limit
}

case "$cpuclockmaxpredef" in
  0)
    # CPU 2457MHz
    scaling_max_freq="2457600"
    cpuinfo_max_freq="2457600"
    cpufreq_max_limit="2457600"
    cpuclockmax_predef="0"
    write_values
    ;;
  1)
    # CPU 2265MHz
    scaling_max_freq="2265600"
    cpuinfo_max_freq="2265600"
    cpufreq_max_limit="2265600"
    cpuclockmax_predef="1"
    write_values
    ;;
  2)
    # CPU 1958MHz
    scaling_max_freq="1958400"
    cpuinfo_max_freq="1958400"
    cpufreq_max_limit="1958400"
    cpuclockmax_predef="2"
    write_values
    ;;
  3)
    # CPU 1728MHz
    scaling_max_freq="1728000"
    cpuinfo_max_freq="1728000"
    cpufreq_max_limit="1728000"
    cpuclockmax_predef="3"
    write_values
    ;;
  4)
    # CPU 1574MHz
    scaling_max_freq="1574400"
    cpuinfo_max_freq="1574400"
    cpufreq_max_limit="1574400"
    cpuclockmax_predef="4"
    write_values
    ;;
  5)
    # CPU 1497MHz
    scaling_max_freq="1497600"
    cpuinfo_max_freq="1497600"
    cpufreq_max_limit="1497600"
    cpuclockmax_predef="5"
    write_values
    ;;
  6)
    # CPU 1267MHz
    scaling_max_freq="1267200"
    cpuinfo_max_freq="1267200"
    cpufreq_max_limit="1267200"
    cpuclockmax_predef="6"
    write_values
    ;;
  7)
    # CPU 1190MHz
    scaling_max_freq="1190400"
    cpuinfo_max_freq="1190400"
    cpufreq_max_limit="1190400"
    cpuclockmax_predef="7"
    write_values
    ;;
  8)
    # CPU 1036MHz
    scaling_max_freq="1036800"
    cpuinfo_max_freq="1036800"
    cpufreq_max_limit="1036800"
    cpuclockmax_predef="8"
    write_values
    ;;
  9)
    # CPU 960MHz
    scaling_max_freq="960000"
    cpuinfo_max_freq="960000"
    cpufreq_max_limit="960000"
    cpuclockmax_predef="9"
    write_values
    ;;
  10)
    # CPU 883MHz
    scaling_max_freq="883200"
    cpuinfo_max_freq="883200"
    cpufreq_max_limit="883200"
    cpuclockmax_predef="10"
    write_values
    ;;
  11)
    # CPU 729MHz
    scaling_max_freq="729600"
    cpuinfo_max_freq="729600"
    cpufreq_max_limit="729600"
    cpuclockmax_predef="11"
    write_values
    ;;
  12)
    # CPU 652MHz
    scaling_max_freq="652800"
    cpuinfo_max_freq="652800"
    cpufreq_max_limit="652800"
    cpuclockmax_predef="12"
    write_values
    ;;
  13)
    # CPU 422MHz
    scaling_max_freq="422400"
    cpuinfo_max_freq="422400"
    cpufreq_max_limit="422400"
    cpuclockmax_predef="13"
    write_values
    ;;
  14)
    # CPU 300MHz
    scaling_max_freq="300000"
    cpuinfo_max_freq="300000"
    cpufreq_max_limit="300000"
    cpuclockmax_predef="14"
    write_values
    ;;
  *)
    if [[ ! -z $cpuclockmax_find ]]; then
      cpuclockmax_predef="$cpuclockmax_find"
    fi 
    ;;
esac;

eval echo $cpuclockmax_predef
