#!/system/bin/sh

if [[ ! -z $2 ]]; then
    filename=$(basename $2)
fi

if [[ ! -z $3 ]]; then
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
fi

minfree_predef="0"
minfree_find=`grep "minfree_predef" $DEFAULT_PROFILE | cut -d'=' -f2`

write_value() {  
  echo "$1=$2" >> $DEFAULT_PROFILE
}

edit_value() {
  g_find=`grep $1=.* $DEFAULT_PROFILE`
    
  if [[ -z $g_find ]]; then
    write_value $1 $2
  else
    sed -i "s/$1=[^ ]*/$1=$2/" $DEFAULT_PROFILE 
  fi
}

write_values(){
  edit_value minfree_lkm $minfree_lkm
  edit_value minfree_predef $minfree_predef 

  chmod 777 /sys/module/lowmemorykiller/parameters/minfree
  echo $minfree_lkm > /sys/module/lowmemorykiller/parameters/minfree
  chmod 0644 /sys/module/lowmemorykiller/parameters/minfree
}

case "$minfreepredef" in
  0)
    # LMK: Normal (stock)
    # Forground apps    : 12288 pages /  48Mb
    # Visible apps      : 15360 pages /  60Mb
    # Secondary server  : 18432 pages /  72Mb
    # Hidden apps       : 21504 pages /  84Mb
    # Content providers : 24576 pages /  96Mb
    # Emtpy apps        : 30720 pages / 120Mb
    minfree_lkm="12288,15360,18432,21504,24576,30720"
    minfree_predef="0"
    write_values
    ;;
  1)
    # LMK: Moderado (Javilonas)
    # Forground apps    : 12288 pages /  48Mb
    # Visible apps      : 15360 pages /  60Mb
    # Secondary server  : 18432 pages /  72Mb
    # Hidden apps       : 21504 pages /  84Mb
    # Content providers : 32768 pages / 128Mb
    # Emtpy apps        : 49152 pages / 192Mb
    minfree_lkm="12288,15360,18432,21504,32768,49152"
    minfree_predef="1"
    write_values
    ;;
  2)
    # LMK: Super Moderado (Javilonas)
    # Forground apps    : 12288 pages /  48Mb
    # Visible apps      : 15360 pages /  60Mb
    # Secondary server  : 21504 pages /  84Mb
    # Hidden apps       : 32768 pages / 128Mb
    # Content providers : 49152 pages / 192Mb
    # Emtpy apps        : 65536 pages / 256Mb
    minfree_lkm="12288,15360,21504,32768,49152,65536"
    minfree_predef="2"
    write_values
    ;;
  3)
    # LMK: Light
    # Forground apps    : 1024 pages /  4Mb
    # Visible apps      : 2048 pages /  8Mb
    # Secondary server  : 2560 pages / 10Mb
    # Hidden apps       : 4096 pages / 16Mb
    # Content providers : 6144 pages / 24Mb
    # Emtpy apps        : 8192 pages / 32Mb
    minfree_lkm="1024,2048,2560,4096,6144,8192"
    minfree_predef="3"
    write_values
    ;;
  4)
    # LMK: Super Light
    # Forground apps    :  512 pages /  2Mb
    # Visible apps      : 1024 pages /  4Mb
    # Secondary server  : 1280 pages /  5Mb
    # Hidden apps       : 2048 pages /  8Mb
    # Content providers : 3072 pages / 12Mb
    # Emtpy apps        : 4096 pages / 16Mb
    minfree_lkm="512,1024,1280,2048,3072,4096"
    minfree_predef="4"
    write_values
    ;;
  5)
    # LMK: Medio
    # Forground apps    :  1024 pages /  4Mb
    # Visible apps      :  2048 pages /  8Mb
    # Secondary server  :  4096 pages / 16Mb
    # Hidden apps       :  8192 pages / 32Mb
    # Content providers : 12288 pages / 48Mb
    # Emtpy apps        : 16384 pages / 64Mb
    minfree_lkm="1024,2048,4096,8192,12288,16384"
    minfree_predef="5"
    write_values
    ;;
  6)
    # LMK: Agresivo
    # Forground apps    :  2048 pages /   8Mb
    # Visible apps      :  4096 pages /  16Mb
    # Secondary server  :  8192 pages /  32Mb
    # Hidden apps       : 16384 pages /  64Mb
    # Content providers : 24576 pages /  96Mb
    # Emtpy apps        : 32768 pages / 128Mb
    minfree_lkm="2048,4096,8192,16384,24576,32768"
    minfree_predef="6"
    write_values
    ;;
  7)
    # LMK: Super Agresivo
    # Forground apps    :  4096 pages /  16Mb
    # Visible apps      :  8192 pages /  32Mb
    # Secondary server  : 16384 pages /  64Mb
    # Hidden apps       : 32768 pages / 128Mb
    # Content providers : 49152 pages / 192Mb
    # Emtpy apps        : 65536 pages / 256Mb
    minfree_lkm="4096,8192,16384,32768,49152,65536"
    minfree_predef="7"
    write_values
    ;;
  *)
    if [[ ! -z $minfree_find ]]; then
      minfree_predef="$minfree_find"
    fi 
    ;;
esac;

eval echo $minfree_predef
