#!/system/bin/sh
export PATH="/res/lpowercc/actions/push-actions:${PATH}";

if [ "a$2" == "a" ]; then
	echo "$debug_to_sd";
else
	debug_to_sd=$2;
	echo "$debug_to_sd";
fi;

DEBUG_FILE="/sdcard/lpowercc_debug";
DEBUG_FILE_LOGCAT="/sdcard/lpowercc_debug_logcat";

PROFILE=`cat /data/.lpowercc/.active.profile`;
. /data/.lpowercc/${PROFILE}.profile;

case "${debug_to_sd}" in
	1)
		(

			SEPARATOR()
			{
				echo "" >> $DEBUG_FILE;
				echo " ---------------------------- " >> $DEBUG_FILE;
				echo "" >> $DEBUG_FILE;
			}

			# more debug
			echo "1" > /sys/module/kernel/parameters/initcall_debug;
			echo "2" > /sys/module/lowmemorykiller/parameters/debug_level;
			echo "1" > /sys/module/earlysuspend/parameters/debug_mask;
			echo "1" > /sys/module/alarm/parameters/debug_mask;
			echo "1" > /sys/module/alarm_dev/parameters/debug_mask;
			echo "1" > /sys/module/binder/parameters/debug_mask;
			echo "1" > /sys/module/xt_qtaguid/parameters/debug_mask;

			# overwrite old debug-file
			echo "" > $DEBUG_FILE;
			echo " --- DEBUG from "`date`" --- " >> $DEBUG_FILE;
			echo "" >> $DEBUG_FILE;

			# Kernel-Info
			echo "Kernel-Version:" >> $DEBUG_FILE;
			cat /proc/version >> $DEBUG_FILE;
			SEPARATOR;

			date +"Last Reboot: %d.%m.%y / %H:%m" -d @$(( $(date +%s) - $(cut -f1 -d. /proc/uptime) )) >> $DEBUG_FILE;
			SEPARATOR;

			# System
			echo "ROM-Version:" >> $DEBUG_FILE;
			cat init.rc | grep "# THIS INIT.RC is FOR" >> $DEBUG_FILE;
			getprop ro.modversion >> $DEBUG_FILE;
			getprop cm.version >> $DEBUG_FILE;
			getprop ro.build.description >> $DEBUG_FILE;
			getprop ro.build.date >> $DEBUG_FILE;
			getprop ro.build.display.id >> $DEBUG_FILE;
			getprop ro.build.id >> $DEBUG_FILE;
			SEPARATOR;

			# Profile
			PROFILE=`cat /data/.lpowercc/.active.profile`;
			echo "Profile-Config: $PROFILE" >> $DEBUG_FILE;
			cat /data/.lpowercc/${PROFILE}.profile >> $DEBUG_FILE;
			SEPARATOR;

			# Memory
			echo "Memory-Info:" >> $DEBUG_FILE;
			free >> $DEBUG_FILE;
			cat /proc/swaps >> $DEBUG_FILE;
			cat /proc/meminfo >> $DEBUG_FILE;
			SEPARATOR;

			# low mem kill info
			echo "App-Info for 'low memory killer':" >> $DEBUG_FILE;
			for i in `ls /proc/ | grep -E '^[0-9]+'`; do
				if [ "$i" -ne 0 ] && [ -f  "/proc/$i/oom_score_adj" ] && [ "`cat /proc/$i/cmdline`" ]; then
					echo "" >> $DEBUG_FILE;
					cat /proc/$i/oom_score_adj >> $DEBUG_FILE;
					cat /proc/$i/cmdline >> $DEBUG_FILE;
					echo "" >> $DEBUG_FILE;
				fi;
			done;
			SEPARATOR;

			# CPU
			echo "CPU-Info:" >> $DEBUG_FILE;
			scaling_governor=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
			echo "CPU-Governor: $scaling_governor" >> $DEBUG_FILE;
			cpuinfo_cur_freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq);
			echo "Cur.-Freq: $cpuinfo_cur_freq" >> $DEBUG_FILE;
			scaling_max_freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq);
			echo "Max.-Freq: $scaling_max_freq" >> $DEBUG_FILE;
			scaling_min_freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq);
			echo "Min.-Freq: $scaling_min_freq" >> $DEBUG_FILE;
			total_trans=$(cat /sys/devices/system/cpu/cpu0/cpufreq/stats/total_trans);
			echo "Total freq-switch: $total_trans" >> $DEBUG_FILE;
			echo "" >> $DEBUG_FILE;
			echo "Time-In-State:" >> $DEBUG_FILE;
			cat /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state >> $DEBUG_FILE;
			for i in `cat /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state | cut -f 2 -d ' '`; do
				summe=$(($summe+$i));
			done;
			summe=$(($summe/100));
			summe=$(($summe/60));
			if [ $summe -lt 60 ]; then
				echo "uptime with CPU on: $summe min" >> $DEBUG_FILE;
			else
				summe=$(($summe/60));
				echo "uptime with CPU on: $summe h" >> $DEBUG_FILE;
			fi;
			echo "" >> $DEBUG_FILE;
			echo "Uptime:" >> $DEBUG_FILE;
			uptime >> $DEBUG_FILE;
			SEPARATOR;

			echo "more CPU-Infos:" >> $DEBUG_FILE;
			cpuinfo_cur_freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq);
			for i in `ls /sys/devices/system/cpu/cpu0/cpufreq/`; do
				if [ ! -d "/sys/devices/system/cpu/cpu0/cpufreq/${i}" ]; then
					echo $i >> $DEBUG_FILE;
					cat /sys/devices/system/cpu/cpu0/cpufreq/$i >> $DEBUG_FILE 2>&1;
					echo "" >> $DEBUG_FILE;
				fi;
			done;
			SEPARATOR;

			# Interrupts
			echo "Interrupts-Info:" >> $DEBUG_FILE;
			cat /proc/interrupts >> $DEBUG_FILE;
			SEPARATOR;

			# Wakeup
			echo "Wakeup-Info:" >> $DEBUG_FILE;
			cat /sys/kernel/debug/wakeup_sources >> $DEBUG_FILE;
			SEPARATOR;

			# Suspend
			echo "Suspend-Info:" >> $DEBUG_FILE;
			cat /sys/kernel/debug/suspend_stats >> $DEBUG_FILE;
			SEPARATOR;

			# NET
			echo "NET-Info:" >> $DEBUG_FILE;
			ifconfig pdp0 >> $DEBUG_FILE;
			ifconfig wlan0 >> $DEBUG_FILE;
			SEPARATOR;

			# USB
			echo "USB-Info:" >> $DEBUG_FILE;
			lsusb >> $DEBUG_FILE;
			SEPARATOR;

			# lsmod
			echo "lsmod-Info:" >> $DEBUG_FILE;
			lsmod >> $DEBUG_FILE;
			SEPARATOR;

			# Partitions
			echo "Partitions-Info:" >> $DEBUG_FILE;
			mount >> $DEBUG_FILE;
			cat /proc/partitions >> $DEBUG_FILE;
			SEPARATOR;

			# Partitions status
			echo "DATA Partition" >> $DEBUG_FILE;
			/sbin/tune2fs -l /res/dev/data | grep 'Filesystem state' | cut -c 27-44 >> $DEBUG_FILE;
			echo "SYSTEM Partition" >> $DEBUG_FILE;
			/sbin/tune2fs -l /res/dev/system | grep 'Filesystem state' | cut -c 27-44 >> $DEBUG_FILE;
			echo "CACHE Partition" >> $DEBUG_FILE;
			/sbin/tune2fs -l /res/dev/cache | grep 'Filesystem state' | cut -c 27-44 >> $DEBUG_FILE;
			echo "EFS Partition" >> $DEBUG_FILE;
			/sbin/tune2fs -l /dev/block/mmcblk0p13 | grep 'Filesystem state' | cut -c 27-44 >> $DEBUG_FILE;
			echo "Preloaded Partition" >> $DEBUG_FILE;
			/sbin/tune2fs -l /dev/block/mmcblk0p26 | grep 'Filesystem state' | cut -c 27-44 >> $DEBUG_FILE;
			SEPARATOR;

			# System
			echo "System-Info:" >> $DEBUG_FILE;
			echo "sysctl:" >> $DEBUG_FILE;
			sysctl -a >> $DEBUG_FILE;
			echo "" >> $DEBUG_FILE;
			echo "getprop:" >> $DEBUG_FILE;
			getprop >> $DEBUG_FILE;
			SEPARATOR;

			# Processes
			echo "Process-Info: top" >> $DEBUG_FILE;
			top -b -n 1 >> $DEBUG_FILE;
			SEPARATOR;

			echo "Process-Info: ps" >> $DEBUG_FILE;
			ps -w >> $DEBUG_FILE;
			SEPARATOR;

			echo "Process-Info: nice (priority)" >> $DEBUG_FILE;
			for z in `ls /proc/*/stat`; do
				tmp=`cat $z` && echo $tmp | cut -f 2 -d ' ' >> $DEBUG_FILE && echo $tmp | cut -f 19 -d ' ' >> $DEBUG_FILE && echo " " >> $DEBUG_FILE;
			done;
			SEPARATOR;

			# dmesg
			echo "dmesg-Info:" >> $DEBUG_FILE;
			dmesg >> $DEBUG_FILE;
			SEPARATOR;

			echo "dmesg-Error:" >> $DEBUG_FILE;
			dmesg | grep -i "Error" >> $DEBUG_FILE;
			SEPARATOR;

			echo "dmesg-Warning:" >> $DEBUG_FILE;
			dmesg | grep -i "Warning" >> $DEBUG_FILE;
			SEPARATOR;

			echo "dmesg-Fail:" >> $DEBUG_FILE;
			dmesg | grep -i "Fail" >> $DEBUG_FILE;
			SEPARATOR;

			if [ "$logger" == "off" ]; then
				echo "0" > /sys/module/kernel/parameters/initcall_debug;
				echo "1" > /sys/module/lowmemorykiller/parameters/debug_level;
				echo "0" > /sys/module/earlysuspend/parameters/debug_mask;
				echo "0" > /sys/module/alarm/parameters/debug_mask;
				echo "0" > /sys/module/alarm_dev/parameters/debug_mask;
				echo "0" > /sys/module/binder/parameters/debug_mask;
				echo "0" > /sys/module/xt_qtaguid/parameters/debug_mask;
			fi;
		)&
		echo "All Data collected and ready at $DEBUG_FILE";
	;;
	2)
		# logcat
		(
			# overwrite old debug-file
			echo "" > $DEBUG_FILE_LOGCAT;

			logcat -f $DEBUG_FILE_LOGCAT;

			wait 60;
			pkill logcat;
			#maybe we can also grep / remove personal infos here (e.g . email address)
		)&
		echo "Collecting logs for 60Sec please wait";
	;;
	*)
		echo "need input";
	;;
esac;
